//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileMappingEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileMappingEngine.Resources.UiMessages", typeof(UiMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column after.
        /// </summary>
        internal static string ColumnAddAfter {
            get {
                return ResourceManager.GetString("ColumnAddAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column before.
        /// </summary>
        internal static string ColumnAddBefore {
            get {
                return ResourceManager.GetString("ColumnAddBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define formula.
        /// </summary>
        internal static string ColumnFormula {
            get {
                return ResourceManager.GetString("ColumnFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge columns.
        /// </summary>
        internal static string ColumnMerge {
            get {
                return ResourceManager.GetString("ColumnMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove column.
        /// </summary>
        internal static string ColumnRemove {
            get {
                return ResourceManager.GetString("ColumnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove columns.
        /// </summary>
        internal static string ColumnRemovePlural {
            get {
                return ResourceManager.GetString("ColumnRemovePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename column.
        /// </summary>
        internal static string ColumnRename {
            get {
                return ResourceManager.GetString("ColumnRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set data type.
        /// </summary>
        internal static string ColumnSetDt {
            get {
                return ResourceManager.GetString("ColumnSetDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed adding {0};.
        /// </summary>
        internal static string Fail_add {
            get {
                return ResourceManager.GetString("Fail_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to apply {0}!.
        /// </summary>
        internal static string Fail_apply {
            get {
                return ResourceManager.GetString("Fail_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change {0}!.
        /// </summary>
        internal static string Fail_change {
            get {
                return ResourceManager.GetString("Fail_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load {0}!.
        /// </summary>
        internal static string Fail_load {
            get {
                return ResourceManager.GetString("Fail_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove {0}!.
        /// </summary>
        internal static string Fail_remove {
            get {
                return ResourceManager.GetString("Fail_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save {0}!.
        /// </summary>
        internal static string Fail_save {
            get {
                return ResourceManager.GetString("Fail_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saved successfully..
        /// </summary>
        internal static string Success_save {
            get {
                return ResourceManager.GetString("Success_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields!.
        /// </summary>
        internal static string Warning_fillFielfs {
            get {
                return ResourceManager.GetString("Warning_fillFielfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} loaded!.
        /// </summary>
        internal static string Warning_notLoaded {
            get {
                return ResourceManager.GetString("Warning_notLoaded", resourceCulture);
            }
        }
    }
}
